### ISSUE TITLE
Unrecoverable error on fetchDownloadInfo HEAD request failure

### ISSUE THREAD

**Issue by ChlodAlejandro** [ido-pluto/ipull#12]
I'm using ipull to get data from the [UN OCHA Humanitarian Data Exchange](https://data.humdata.org/), which uses Amazon S3 as a file backend. I ran across an oddity related to the implementation of `fetchDownloadInfoWithoutRetry` in [download-engine-fetch-stream-fetch.ts](https://github.com/ido-pluto/ipull/blob/main/src/download/download-engine/streams/download-engine-fetch-stream/download-engine-fetch-stream-fetch.ts#L52). It seems that the function always attempts to make a HEAD request to gather info about the file to be downloaded, unless `defaultFetchDownloadInfo` was provided beforehand. Though theoretically this should be fine (according to the HTTP spec), practically this is incompatible with some [Amazon S3 presigned URLs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html), and likely other S3 implementations with presigning or custom file server implementations.

Pre-signed URLs allow external access to otherwise private S3 bucket objects, which OCHA does with their files. To prevent unauthorized overwriting of files, the specific HTTP verb can be limited to a specific verb. For HDX files, it appears to be limited to `GET`, which (unintuitively) blocks HEAD requests with a `403 Forbidden`. Since `fetchDownloadInfoWithoutRetry` will *always* try to use a HEAD request, and fail with a `StatusCodeError` if it encounters a 403, it will always fail for this type of presigned URL.

Luckily, for this specific setup, the workaround is setting `defaultFetchDownloadInfo` beforehand (see [example](https://github.com/ChlodAlejandro/philippine-adm-maps/blob/24f7b0cc3d144f640e7740e186d03ea4d353228f/src/init.ts#L90); finding this was hard since it appears to be undocumented?), with the [length as provided by the HDX CKAN API](https://data.humdata.org/api/3/action/package_show?id=cod-ab-phl) (`.resources[*].size`) and with `acceptRange` hardcoded to "true" (as Amazon S3 is always able to resume an interrupted download).

A possible solution would be to non-fatally handle the error and keep downloading with no progress bar (similar to pretending that `Content-Length` is unset; only if `cliProgress` is `true`, of course) and/or grab the `Accept-Ranges` and `Content-Length` data from the actual `GET` request, and use *that* information to render the progress bar. Of course, other solutions are welcome if you have any!

**Comment by ido-pluto** [comment]
Thanks for reporting! 
I believe the best approach is to initiate GET request if the HEAD fails.
Without a Content-Length header, download speeds slow down considerably, so I’m working to prevent that.

I’ll investigate further, and it will be resolved in the next patch :)

**Comment by ido-pluto** [comment]
Fixed in latest version, If it is still does not work feel free to reopen :)
