### ISSUE TITLE
Inconsistent `downloadFile` failure behavior when using `cliProgress` with Node.js API

### ISSUE THREAD

**Issue by ChlodAlejandro** [ido-pluto/ipull#13]
Came across this while debugging #12.

There's some inconsistencies with how `downloadFile` behaves when called with the Node.js API and reaching failure conditions with `cliProgress` enabled. Ideally, every failure state encountered when using the API should throw an error that can be handled by the calling program; `cliProgress` being enabled shouldn't change this behavior.

Note that the below don't occur when `cliProgress` is disabled. Instead, ipull throws the error appropriately, allowing the caller to handle the error. These also don't occur for `.download()`, which appears to have more robust error handling.

## Error not being caught
```js
const downloader = await downloadFile({
    url: "<file_url>",
    cliProgress: true,
    directory: dataPath
});
try {
    await downloader.download();
} catch (e) {
    log.error("Failed to download", e);
    return;
}
```
This appears to show the `Gathering information` spinner, then immediately exits the program with exit code 1, not letting any further catching happen.

## Error being caught
```js
try {
    const downloader = await downloadFile({
        url: "<file_url>",
        cliProgress: true,
        directory: dataPath
    });
    await downloader.download();
} catch (e) {
    log.error("Failed to download", e);
    return;
}
```
This shows the `Gathering information` spinner infinitely until execution is stopped with `^C` (`Ctrl` + `C`). Only then does the error get handled and printed.

**Comment by ido-pluto** [comment]
Thank for reporting!, I will look into that. 
Seems like small fixes, will be fixed in the next patch release.

**Comment by ido-pluto** [comment]
Fixed in latest version, If it is still does not work feel free to reopen :)
