### ISSUE TITLE
Crash when `Invalid content length`

### ISSUE THREAD

**Issue by coderaiser** [ido-pluto/ipull#7]
I have a crash when trying to download a file:

![image](https://github.com/ido-pluto/ipull/assets/1573141/02f51bbe-eb0a-4e33-9a5e-79bb786acd1b)

`wget` works good

**Comment by ido-pluto** [comment]
IPull best downloads large files when he knows the content length before the download, and the split to parallel downloads.

Not all servers send the content length before the downloads :(
I will add a fullback to regular downloads when the content length is not present.

Can you describe your use case?
It will help me understand if there is anything I can do to optimize the download speed

What type of file you are trying to download?
What is the size of the file?
The remote server type: express/php/ngnix

**Comment by coderaiser** [comment]
I want to switch from `wget` to JavaScript CLI to [download two files](https://github.com/putoutjs/quick-lint/blob/a13c68e64deeb414ad6021d876cc3ea069297503/.madrun.js#L17) with `npm run update:dist`.

**Comment by ido-pluto** [comment]
Check out the latest release, this should be fixed. If not please reopen this issue

**Comment by coderaiser** [comment]
Same error in `v3.1.0`:

<img width="934" alt="image" src="https://github.com/ido-pluto/ipull/assets/1573141/6402c249-2199-4020-a413-67f9c6f99885">

**Comment by ido-pluto** [comment]
Seems that the server send invalid response he does not send content length but accept content range, witch does not work with one another.
I will add a fullback in case that the content length does not match the content range

**Comment by coderaiser** [comment]
`wget` works good 🤷

**Comment by ido-pluto** [comment]
Fix on v3.1.1
If there is any other error, feel free to open another issue :)
