### ISSUE TITLE
Wrong size of downloaded file

### ISSUE THREAD

**Issue by coderaiser** [ido-pluto/ipull#8]
Here is link: https://quick-lint-js.com/demo/dist/quick-lint-js-vscode.wasm

<img width="593" alt="image" src="https://github.com/ido-pluto/ipull/assets/1573141/2271d217-1a6d-4587-909d-b485359357e0">

`wget` has 470K, and `ipull` for some reason has `5M`.

Nice progress bar, by the way :)

**Comment by ido-pluto** [comment]
Thank you, should be fixed in the latest release :)
